directories:
  output: release
  buildResources: build
appId: io.github.chickenpoo.survevwrapper
productName: ChickenPoo's Amazing Survev Client
artifactName: chickenpoo-survev-wrapper-setup-${version}.${ext}
files:
  - filter:
      - main.js
      - preload.js
      - mods/**/*
      - skins/**/*
      - package.json
win:
  target: nsis
  forceCodeSigning: false
publish:
  - provider: github
    owner: chickenpoo351
    repo: chickenPoo-amazing-survev-client-desktop
electronDownload:
  mirror: https://github.com/electron/electron/releases/download/
electronVersion: 39.2.7
